server:
  port: 8000
  host: 0.0.0.0
db:
  host: localhost
  port: 5432
  user: postgres
  password: DB_PASS_ENV
  db_name: DemoDatabase
jwt:
  duration_minutes: 15
  refresh_duration_minutes: 15
  signing_algorithm: HS256
  signing_key_env: SIGNING_KEY_ENV
